<%@ Page Language="C#" MasterPageFile="~/PrimaryTemplate.Master" StylesheetTheme="ThemeA_1024"
    AutoEventWireup="true" CodeBehind="GrowerBooks.aspx.cs" Inherits="WSCIEMP.Reports.GrowerBooks"
    Title="Western Sugar Cooperative - Grower Books" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitleHolder" runat="server">
    Grower Books
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentCenter" runat="server">
    <div style="width: 100%; text-align: center;">
        <table class="wideTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td style="width:100%;">
                    <br />
                    <p>
                        <span class="ButtonText">Expand the folders as needed to find documents. All documents will
                            open in a new browser window.</span>
                    </p>
                </td>
            </tr>
            <tr>
                <td class="ButtonText" style="vertical-align:top; text-align:left;">
                    <br />
                    <div id="FolderViewer">
                        <asp:TreeView ID="tvwBrowse" runat="server" 
                            ontreenodepopulate="tvwBrowse_TreeNodePopulate" ShowExpandCollapse="true"
                            AutoGenerateDataBindings="false" ExpandDepth="1" BorderColor="Black" BorderStyle="Solid" BorderWidth="1px"
                            ExpandImageUrl="~/img/folders/lp.gif" CollapseImageUrl="~/img/folders/lm.gif" LeafNodeStyle-ImageUrl="~/img/folders/ln.gif">
                            <NodeStyle CssClass="ButtonText" />
                            <Nodes>
                                <asp:TreeNode NavigateUrl="~/ZHost/Grower Books" Text="Grower Books" SelectAction="Select" PopulateOnDemand="true"></asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </div>
                </td>
            </tr>
            <tr><td style="line-height:75px;">&nbsp;</td></tr>
        </table>
    </div>
</asp:Content>
